doan_cd2_nhom6/app_social/urls.py
from django.urls import path
from app_social import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index,name='index'),
    path('profile', views.profile,name='profile'),
   
    path('editProfile/<int:user_id>', views.editProfile,name='editProfile'),
    path('update_avatar/<int:user_id>', views.update_avatar,name='update_avatar'),
    path('profile/group', views.group,name='group'),
    path('join_group/<int:group_id>/', views.join_group, name='join_group'),
    path('group/<int:group_id>/', views.group_detail, name='group_detail'),
    path('registe/', views.register,name='register'),
      path('edit_Grouppost/<int:post_id>/', views.edit_Grouppost, name='edit_Grouppost'),
    path('login/', views.user_login,name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/allFriends', views.allFriends, name='All_friends'),
    path('profile/<str:username>/', views.user_profile_view, name='user_profile'),
    path('send_friend_request/<str:friend_username>/', views.send_friend_request, name='send_friend_request'),
    path('friend_requests/', views.friend_requests, name='friend_requests'),
    path('accept_friend_request/<int:friend_request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:friend_request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('user_profile/<int:user_id>/', views.user_friends, name='user_profileFriends'),
    path('create_post/', views.create_post, name='create_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    # path('profile/allFollwers', views.allFollowers, name='All_followers'),
    # path('user_profile/<int:user_id>/allFollwers', views.user_Followers, name='user_profileFollowers'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('search/', views.result_search, name='result_search'),
    path('comment/<int:post_id>', views.comment_post, name='commentPost'),
    path('group/<int:group_id>/leave/', views.leave_group, name='leave_group'),
    path('profile/allFriends/unfriend/<int:friendship_id>/', views.unfriend, name='unfriend'),
    path('profile/allFriends/blocked/<int:friendship_id>/', views.block_friend, name='blocked'),
    path('profile/blockedFriends', views.blockingFriends, name='blockingFriends'),
    path('unblock/<int:friendship_id>/', views.unblock, name='unblock'),
    path('list_group/', views.List_view_group, name='list_group'),
    path('group/<int:group_id>/delete/', views.delete_group, name='delete_group'),
    path('group/<int:group_id>/edit/', views.editGroup, name='edit_group'),
    path('like_Grouppost/<int:post_id>/<int:group_id>/', views.like_Grouppost, name='like_post_group'),
    path('commentGroup/<int:post_id>', views.comment_Grouppost, name='commentGroupPost'),
    path('delete_commentGroupPost/<int:comment_id>', views.deleteCommentGroupPost, name='deleteCommentGroupPost'),
    path('commentReply/<int:post_id>', views.commentReplyPost, name='commentReplyPost'),
    path('deleteReplyCommentPost/<int:comment_id>', views.deleteReplyCommentPost, name='deleteReplyCommentPost'),
    path('commentReplyGroup/<int:post_id>', views.comment_GroupReplypost, name='commentGroupReplyPost'),
    path('deleteReplyCommentGroupPost/<int:reply_id>', views.deleteReplyCommentGroupPost, name='deleteReplyCommentGroupPost'),
   
    path('comment/<int:post_id>', views.comment_post, name='commentPost'),
    path('delete_comment/<int:comment_id>', views.deleteComment, name='deleteComment'),
    path('group/<int:group_id>/edit/', views.editGroup, name='edit_group'),
    path('form_fanpage', views.form_Fanpage, name='form_fanpage'),
    path('fanpage/<int:page_id>', views.fanpage, name='fanpage'),
    path('create_fanpage', views.create_fanpage, name='create_fanpage'),
    path('post_fanpage', views.create_post_fanpage, name='create_post_fanpage'),
    path('edit_fanpage', views.edit_fanpage, name='edit_fanpage'),
    path('delete_fanpage/<int:page_id>', views.delete_fanpage, name='delete_fanpage'),
    path('edit_post_fanpage/<int:post_id>', views.edit_post_fanpage, name='edit_post_fanpage'),
    path('delete_post_fanpage/<int:post_id>', views.delete_post_fanpage, name='delete_post_fanpage'),
    path('join_fanpage/<int:page_id>', views.join_fanpage, name='join_fanpage'),
    path('leave_fanpage/<int:page_id>', views.leave_fanpage, name='leave_fanpage'),
    path('like_fanpage/<int:page_id>', views.like_fanpage, name='like_fanpage'),
    path('unlike_fanpage/<int:page_id>', views.unlike_fanpage, name='unlike_fanpage'),
    path('list_page/', views.list_page, name='list_page'),
    path('like_Userpost/<int:post_id>/', views.like_Userpost, name='like_Userpost'),
    path('like_post_fanpage/<int:post_id>', views.like_post_fanpage, name='like_post_fanpage'),
     path('comment_post_fanpage/<int:post_id>', views.comment_post_fanpage, name='comment_post_fanpage'),
    path('deleteCommentFanpage/<int:comment_id>', views.deleteCommentFanpage, name='deleteCommentFanpage'),
    path('commentUserPost/<int:post_id>', views.comment_Userpost, name='commentUserPost'),


]

doan_cd2_nhom6/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='homechat'),
    path('<str:room_name>/', views.room, name='room'),
]

doan_cd2_nhom6/project_social_network/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_social.urls','app_social'),namespace='app_social')),
    # path('auth/', include('authentication.urls')),
    path('chat/', include('chat.urls')),
    path('', RedirectView.as_view(url='/chat/')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doan_cd2_nhom6/app_social/forms.py
from .models import CustomUser,Post,Comment,Like,Friendship,Group,GroupPost,ReplyComment
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm


class createGroup(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name','description','group_picture']

class GroupPostForm(forms.ModelForm):
    class Meta:
        model = GroupPost
        fields = ['content']
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = ReplyComment
        fields = ['text']

class CustomUserCreationForm(UserCreationForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=CustomUser.GENDER_CHOICES, widget=forms.RadioSelect)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2', 'first_name' ,'last_name','email', 'date_of_birth', 'gender', 'avatar')
        
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')
        
class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = CustomUser
        fields = ('old_password', 'new_password1','new_password2')

doan_cd2_nhom6/app_social/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import createGroup,GroupPostForm,CommentForm,ReplyCommentForm,CustomUserCreationForm,CustomAuthenticationForm,CustomPasswordChangeForm
from .models import Group,GroupPost,Comment,CustomUser,FriendRequest,Video,Friendship,Post,Image,Follow,CommentPost,ReplyCommentPost,Fanpage,CommentFanpage,ReplyComment,ReplyCommentFanpage,Post_Fanpage,VideoFanpage,ImageFanpage
from django.contrib.auth import login,update_session_auth_hash
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib.auth.tokens import default_token_generator
import random
import string
from django.contrib.auth.hashers import make_password
def index(request):
    fanpage = Fanpage.objects.order_by('-created_at')
    posts = Post.objects.order_by('-created_at')
    comments = CommentPost.objects.order_by('-created_at')
    
    reply_comment_post = ReplyCommentPost.objects.order_by('-created_at')
    if(request.user):
     user = request.user
     
     for post_id in posts.all():
            post = posts.get(id=post_id.id)
            if user in post.likes.all():
                post.liked = True
            else:
                post.liked = False
            post.save()
     if not isinstance(user, AnonymousUser):
         user_groups = user.groups_joined.all()
         friends = Friendship.objects.filter(user1=user,blocked=False)
         user = request.user
         all_groups = Group.objects.exclude(members=user)
         suggested_friends = CustomUser.objects.exclude(id=user.id)
         sent_friend_requests = FriendRequest.objects.filter(from_user=user, is_accepted=False).values_list('to_user', flat=True)
         suggested_friends = suggested_friends.exclude(id__in=sent_friend_requests)
         user_friends = Friendship.objects.filter(user1=user).values_list('user2', flat=True)
         suggested_friends = suggested_friends.exclude(id__in=user_friends)
         context = {
         'user':user,
         'suggested_friends': suggested_friends,
         'user_groups': user_groups,
         'all_groups': all_groups,
         'posts': posts,
         'comments': comments,
         'reply_comment_post': reply_comment_post,
         'fanpage': fanpage,
         'friendss': friends
         
         }
         return render(request, 'home.html', context)
    return render(request,"home.html",{'posts': posts})
@login_required(login_url='app_social:login')
def List_view_group(request):
    user = request.user
    user_groups = user.groups_joined.all()
    user = request.user
    all_groups = Group.objects.exclude(members=user)
    context = {
        'user_groups': user_groups,
         'all_groups': all_groups,
    }
    return render(request, 'timeline-groups.html', context)
def user_profile_view(request,username):
    if request.user.is_authenticated:
        custom_user = CustomUser.objects.get(username=username) 
        friends = Friendship.objects.filter(user1=custom_user)
        for friend in friends:
            if friend.user2 == request.user:
                custom_user.isFriendView = True
        is_blocked_by_current_user = Friendship.objects.filter(user1=request.user, user2=custom_user, blocked=True).exists()
        if(is_blocked_by_current_user):
         return redirect(reverse('app_social:blockingFriends') + '?show_alert=true')
        is_blocked_by_user =  Friendship.objects.filter(user1=custom_user, user2=request.user, blocked=True).exists()
        if is_blocked_by_user:
         return redirect(reverse('app_social:index') + '?blocked=true')
        following_users = request.user.following.all()
        is_following = following_users.filter(following__id=custom_user.id).exists()
        request.session['is_following'] = is_following
        if(custom_user==request.user):
            return redirect('app_social:profile')
        posts = Post.objects.filter(author=custom_user,profile__isnull=True).union(Post.objects.filter(profile=custom_user)).order_by('-created_at')
        for post in posts.all():
            if request.user in post.likes.all():
                post.liked = True
            else:
                post.liked = False
            post.save()
        comments = CommentPost.objects.order_by('-created_at')
        reply_comment_post = ReplyCommentPost.objects.order_by('-created_at')
        context = {
            'profile_user': custom_user,
            'posts': posts,
            'comments': comments,
            'reply_comment_post': reply_comment_post,
            'friends' : friends
        }
        return render(request, 'user_profile1.html', context)
    else:
        return redirect('app_social:login')

def leave_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    
    if request.method == 'POST':
        if group.leave_group(request.user):
            return redirect('app_social:list_group')
        
def unfriend(request, friendship_id):
    if request.method == 'POST':
        current_user_id = request.user.id
        friendship = Friendship.objects.filter(
            user1_id=current_user_id, user2_id=friendship_id
        ).first()
        friendship.unfriend()
        userInfo = request.user
        friends = Friendship.objects.filter(user1=userInfo)
        context = {
        'friends': friends
        }
        return render(request,"all_friends.html",context)
    
   
def block_friend(request, friendship_id):
    current_user_id = request.user.id
    if request.method == 'POST':
        friendship = Friendship.objects.filter(
            user1_id=current_user_id, user2_id=friendship_id
         ).first()
        friendship.block()
        userInfo = request.user
        friends = Friendship.objects.filter(user1=userInfo,blocked=False)
        context = {
        'friends': friends
        }
        return render(request,"all_friends.html",context)
    
def unblock(request, friendship_id):
    current_user_id = request.user.id
    if request.method == 'POST':
        friendship = Friendship.objects.filter(
            user1_id=current_user_id, user2_id=friendship_id
         ).first()
        friendship.unblock()
        return redirect('app_social:blockingFriends') 


# def user_profile(request, user_id):
#     user = CustomUser.objects.get(id=user_id)
#     friends = Friendship.objects.filter(user1=user)
#     context = {
#         'userInfos': user,
#         'friends': friends,
#     }
#     return render(request, 'user_friends.html', context)
def user_friends(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    friends = Friendship.objects.filter(user1=user)
    following = user.following.all()
    context = {
        'userInfos': user,
        'friends': friends,
        'followers':following
    }
    return render(request, 'user_friends1.html', context)

def blockingFriends(request):
    blocked_friends_list = request.user.blocked_friends()
    print(blocked_friends_list)
    return render(request, 'blockedFriends1.html', {'blocked_friends': blocked_friends_list})



@login_required(login_url='login')
def allFriends(request):
    user = request.user
    friends = Friendship.objects.filter(user1=user)
    following = user.following.all()
    member_count = friends.count()
    friends = Friendship.objects.filter(user1=user,blocked=False)
    # blocked_friends_list = request.user.blocked_friends()
    # print(blocked_friends_list)
    context = {
        'friends': friends,
        'followers':following,
        'member_count':member_count,
        # 'blocked_friends': blocked_friends_list
    }
    return render(request,"all_friends.html",context)

# def user_Followers(request,user_id):
#     user = CustomUser.objects.get(id=user_id)
#     following = user.following.all()
#     context = {
#         'userInfos': user,
#         'followers':following
#     }
#     return render(request,"user_followers.html",context)
# def allFollowers(request):
#     user = request.user

#     following = user.following.all()
#     context = {
#         'followers':following
#     }
#     return render(request,"followers.html",context)
# def profile(request):
#     userInfo = request.user
#     fanpage = Fanpage.objects.all().order_by('created_at')
#     user_groups = Group.objects.filter(members=request.user)
#     comments = CommentPost.objects.order_by('-created_at')
#     reply_comment_post = ReplyCommentPost.objects.order_by('-created_at')
    
#     posts = Post.objects.filter(author=userInfo,profile__isnull=True).union(Post.objects.filter(profile=userInfo)).order_by('-created_at')
#     for post in posts:
#         if userInfo in post.likes.all():
#             post.liked = True
#         else:
#             post.liked = False
#         post.save() 
    
#     context = {
#          'user_groups': user_groups,
#          'posts': posts,
#          'userInfo': userInfo,
#          'comments': comments,
#          'reply_comment_post': reply_comment_post,
#          'fanpage':fanpage,

#          }
#     return render(request,"time-line.html", context)

@login_required(login_url='app_social:login')
def profile(request):
    userInfo = request.user
    # fanpage = Fanpage.objects.all().order_by('created_at')
    user_groups = Group.objects.filter(members=request.user)
    comments = CommentPost.objects.order_by('-created_at')
    reply_comment_post = ReplyCommentPost.objects.order_by('-created_at')
    
    posts = Post.objects.filter(author=userInfo,profile__isnull=True).union(Post.objects.filter(profile=userInfo)).order_by('-created_at')
    for post in posts:
        if userInfo in post.likes.all():
            post.liked = True
        else:
            post.liked = False
        post.save() 
    
    context = {

doan_cd2_nhom6/app_social/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<title>Winku</title>
	<link rel="icon" href="{% static 'home/images/fav.png' %}" type="image/png" sizes="16x16">

	<link rel="stylesheet" href="{% static 'home/css/main.min.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/color.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">
	{% block head %}{% endblock %}
</head>

<body>
	<!--<div class="se-pre-con"></div>-->
	<div class="theme-layout">

		<div class="responsive-header">
			<div class="mh-head first Sticky">
				<span class="mh-btns-left">
					<a class="" href="#menu"><i class="fa fa-align-justify"></i></a>
				</span>
				<span class="mh-text">
					<a href="/" title=""><img src="{% static 'home/images/logo2.png' %}" alt=""></a>
				</span>
				<span class="mh-btns-right">
					<a class="fa fa-sliders" href="#shoppingbag"></a>
				</span>
			</div>
			<div class="mh-head second">
				<form class="mh-form">
					<input placeholder="search" />
					<a href="/" class="fa fa-search"></a>
				</form>
			</div>


		</div>
		<div class="topbar stick" style="background: #fafafa;">
			<div class="logo">
				<a title="" href="/"><img src="{% static 'home/images/logo.png' %}" alt=""></a>
			</div>

			<div class="top-area">
				{% if user.is_authenticated %}
				<ul class="setting-area">
					<li>
						<a href="#" title="Home" data-ripple=""><i class="ti-search"style="color: black;"></i></a>
					</li>
					<li>
						<a href="{% url 'app_social:index' %}" title="Home" data-ripple="">
							<i class="ti-home" style="color: black;"></i>
						</a>
					</li>
					<li>
						<a href="#" title="Notification" data-ripple="">
							<i class="ti-bell"style="color: black;"></i><span></span>
						</a>
						<div class="dropdowns">
							<span>New Notifications</span>							
							<ul class="drops-menu">
								{% for friend in received_requests %}
								<li>
									<a href="notifications.html" title="">
										<img src="/media/{{friend.from_user.avatar}}" alt="">
										<div class="mesg-meta">
											<h6>{{friend.from_user.username}}</h6>
											<span> 
												<a  class="btn btn-success btn-xs glyphicon glyphicon-ok" href="{% url 'app_social:accept_friend_request' friend.id %}" title="accpet">v</a>
												<a  class="btn btn-danger  btn-xs glyphicon glyphicon-trash" href="{% url 'app_social:reject_friend_request' friend.id %}" title="reject">x</a>
											</span>
											<i>2 min ago</i>
										</div>
									</a>
									<span class="tag green">New</span>
								</li>
								{% endfor %}
							</ul>
						
							<a href="{% url 'app_social:friend_requests' %}" title="" class="more-mesg">view more</a>
						</div>
					</li>
					<li>
						<a href="#" title="Messages" data-ripple=""><i class="ti-comment"style="color: black;"></i><span>12</span></a>
						<div class="dropdowns">
							<span>5 New Messages</span>
							<ul class="drops-menu">
								<li>
									<a href="notifications.html" title="">
										<img src="images/resources/thumb-1.jpg" alt="">
										<div class="mesg-meta">
											<h6>sarah Loren</h6>
											<span>Hi, how r u dear ...?</span>
											<i>2 min ago</i>
										</div>
									</a>
									<span class="tag green">New</span>
								</li>




							</ul>
							<a href="messages.html" title="" class="more-mesg">view more</a>
						</div>
					</li>
					<li><a href="#" title="Languages" data-ripple=""><i class="fa fa-globe"style="color: black;"></i></a>
						<div class="dropdowns languages">
							<a href="#" title=""><i class="ti-check"></i>English</a>
							<a href="#" title="">Arabic</a>
							<a href="#" title="">Dutch</a>
							<a href="#" title="">French</a>
						</div>
					</li>
				</ul>

				<div class="user-img">
					<img src="/media/{{ user.avatar }}" alt="" style="width: 59px; height: 60px;">
					<span class="status f-online"></span>
					<!-- <div class="user-setting">
					<a href="#" title=""><i class="ti-target"></i>{{ user.username }}</a>
					<a href="#" title=""><span class="status f-online"></span> online</a>
					<a href="/user_posts/{{ user.id }}" title=""><i class="ti-user"></i> view profile</a>
					<a href="#" title=""><i class="ti-pencil-alt"></i>edit profile</a>					
					<a href="{% url 'app_social:change_password' %}" title=""><i class="ti-settings"></i>Đổi mật khẩu</a>
					<a href="/logout/" title=""><i class="ti-power-off"></i>log out</a>
					
				</div> -->

				</div>
				{% else %}
				<div class="dn" style="margin-bottom: -22px;">
					<a class="navbar_a" href="{% url 'app_social:login' %}">Đăng nhập</a>
					<a class="navbar_a" href="{% url 'app_social:register' %}">Đăng ký</a>
				</div>
				{% endif %}
			</div>


		</div><!-- topbar -->
		{% block body %}
		{% endblock %}

		<footer>
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-4">
						<div class="widget">
							<div class="foot-logo">
								<div class="logo">
									<a href="index-2.html" title=""><img src="images/logo.png" alt=""></a>
								</div>
								<p>
									The trio took this simple idea and built it into the world’s leading carpooling
									platform.
								</p>
							</div>
							<ul class="location">
								<li>
									<i class="ti-map-alt"></i>
									<p>33 new montgomery st.750 san francisco, CA USA 94105.</p>
								</li>
								<li>
									<i class="ti-mobile"></i>
									<p>+1-56-346 345</p>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-4">
						<div class="widget">
							<div class="widget-title">
								<h4>follow</h4>
							</div>
							<ul class="list-style">
								<li><i class="fa fa-facebook-square"></i> <a href="https://web.facebook.com/shopcircut/"
										title="">facebook</a></li>
								<li><i class="fa fa-twitter-square"></i><a href="https://twitter.com/login?lang=en"
										title="">twitter</a></li>
								<li><i class="fa fa-instagram"></i><a href="https://www.instagram.com/?hl=en"
										title="">instagram</a></li>
								<li><i class="fa fa-google-plus-square"></i> <a href="https://plus.google.com/discover"
										title="">Google+</a></li>
								<li><i class="fa fa-pinterest-square"></i> <a href="https://www.pinterest.com/"
										title="">Pintrest</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-4">
						<div class="widget">
							<div class="widget-title">
								<h4>Navigate</h4>
							</div>
							<ul class="list-style">
								<li><a href="about.html" title="">about us</a></li>
								<li><a href="contact.html" title="">contact us</a></li>
								<li><a href="terms.html" title="">terms & Conditions</a></li>
								<li><a href="#" title="">RSS syndication</a></li>
								<li><a href="sitemap.html" title="">Sitemap</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-4">
						<div class="widget">
							<div class="widget-title">
								<h4>useful links</h4>
							</div>
							<ul class="list-style">
								<li><a href="#" title="">leasing</a></li>
								<li><a href="#" title="">submit route</a></li>
								<li><a href="#" title="">how does it work?</a></li>
								<li><a href="#" title="">agent listings</a></li>
								<li><a href="#" title="">view All</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-4">
						<div class="widget">
							<div class="widget-title">
								<h4>download apps</h4>
							</div>
							<ul class="colla-apps">
								<li><a href="https://play.google.com/store?hl=en" title=""><i
											class="fa fa-android"></i>android</a></li>
								<li><a href="https://www.apple.com/lae/ios/app-store/" title=""><i
											class="ti-apple"></i>iPhone</a></li>
								<li><a href="https://www.microsoft.com/store/apps" title=""><i
											class="fa fa-windows"></i>Windows</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

		</footer><!-- footer -->
		<div class="bottombar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<span class="copyright"><a target="_blank" href="https://www.templateshub.net">Templates
								Hub</a></span>
						<i><img src="images/credit-cards.png" alt=""></i>
					</div>
				</div>
			</div>
		</div>
	</div>
	

	<script data-cfasync="false"
		src=" {% static 'home/../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
	<script src="{% static 'home/js/main.min.js' %}"></script>
	<script src="{% static 'home/js/script.js' %}"></script>
	<script src="{% static 'home/js/map-init.js' %}"></script>
	<script src="{% static 'js/group_detail.js' %}"></script>
	<!-- <script src="https://maps.goo gleapis.com/maps/api/js?key=AIzaSyA8c55_YHLvDHGACkQscgbGLtLRdxBDCfI"></script> -->
</body>

</html>

doan_cd2_nhom6/app_social/templates/timeline-groups.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<section>
	<div class="gap gray-bg">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="row" id="page-contents">
						<div class="col-lg-3">
							<aside class="sidebar static">
								<div class="widget">
									<h4 class="widget-title">Shortcuts</h4>
									<ul class="naves">
										<li>
											<i class="ti-clipboard"></i>
											<a href="{% url 'app_social:index' %}" title="">Trang Chủ</a>
										</li>
										<li>
											<i class="ti-clipboard"></i>
											<a href="{% url 'app_social:group' %}" title="">Create Group</a>
										</li>
																											
										
									</ul>
								</div><!-- Shortcuts -->								
							</aside>
						</div><!-- sidebar -->
						<div class="col-lg-6">
							<div class="central-meta">
								<div class="groups">
									<span><i class="fa fa-users"></i> Groups Đã Tạo</span>
								</div>
								<ul class="nearby-contct">
									{% for group in user_groups %}
									<li>
										<div class="nearly-pepls">
											<figure>
												<a href="time-line.html" title="">
													<img src="{{ group.group_picture.url }}"
														alt=""style="    height: 68px;
														width: 73px;"></a>
											</figure>
											<div class="pepl-info">
												<h4><a href="{% url 'app_social:group_detail' group.id %}" title="">{{group.name}}</a></h4>
												<span>{{group.description}}</span>
												<em>32k Members</em>												
											</div>
										</div>
									</li>
									{% endfor %}
								</ul>
								<div class="lodmore"><button class="btn-view btn-load-more"></button></div>
							</div><!-- photos -->
						</div><!-- centerl meta -->
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}